In [1]:
import MeCab

In [3]:
mecab = MeCab.Tagger('-Ochasen')

In [9]:
res = mecab.parse('こんにちは、私はきかがくです')
print(res)

こんにちは	コンニチハ	こんにちは	感動詞		
、	、	、	記号-読点		
私	ワタシ	私	名詞-代名詞-一般		
は	ハ	は	助詞-係助詞		
きか	キカ	きく	動詞-自立	五段・カ行イ音便	未然形
がく	ガク	がく	名詞-一般		
です	デス	です	助動詞	特殊・デス	基本形
EOS



In [10]:
res

'こんにちは\tコンニチハ\tこんにちは\t感動詞\t\t\n、\t、\t、\t記号-読点\t\t\n私\tワタシ\t私\t名詞-代名詞-一般\t\t\nは\tハ\tは\t助詞-係助詞\t\t\nきか\tキカ\tきく\t動詞-自立\t五段・カ行イ音便\t未然形\nがく\tガク\tがく\t名詞-一般\t\t\nです\tデス\tです\t助動詞\t特殊・デス\t基本形\nEOS\n'

In [14]:
text = 'キカガクでは、ディープラーニングを含んだ機械学習や人工知能の教育を行っています。'
res = mecab.parse(text)
print(res)

キカガク	キカガク	キカガク	名詞-一般		
で	デ	で	助詞-格助詞-一般		
は	ハ	は	助詞-係助詞		
、	、	、	記号-読点		
ディープラーニング	ディープラーニング	Deep learning	名詞-固有名詞-一般		
を	ヲ	を	助詞-格助詞-一般		
含ん	フクン	含む	動詞-自立	五段・マ行	連用タ接続
だ	ダ	だ	助動詞	特殊・タ	基本形
機械学習	キカイガクシュウ	機械学習	名詞-固有名詞-一般		
や	ヤ	や	助詞-並立助詞		
人工知能	ジンコウチノウ	人工知能	名詞-固有名詞-一般		
の	ノ	の	助詞-連体化		
教育	キョウイク	教育	名詞-サ変接続		
を	ヲ	を	助詞-格助詞-一般		
行っ	オコナッ	行う	動詞-自立	五段・ワ行促音便	連用タ接続
て	テ	て	助詞-接続助詞		
い	イ	いる	動詞-非自立	一段	連用形
ます	マス	ます	助動詞	特殊・マス	基本形
。	。	。	記号-句点		
EOS



In [17]:
res.split('\n')[:-2]

['キカガク\tキカガク\tキカガク\t名詞-一般\t\t',
 'で\tデ\tで\t助詞-格助詞-一般\t\t',
 'は\tハ\tは\t助詞-係助詞\t\t',
 '、\t、\t、\t記号-読点\t\t',
 'ディープラーニング\tディープラーニング\tDeep learning\t名詞-固有名詞-一般\t\t',
 'を\tヲ\tを\t助詞-格助詞-一般\t\t',
 '含ん\tフクン\t含む\t動詞-自立\t五段・マ行\t連用タ接続',
 'だ\tダ\tだ\t助動詞\t特殊・タ\t基本形',
 '機械学習\tキカイガクシュウ\t機械学習\t名詞-固有名詞-一般\t\t',
 'や\tヤ\tや\t助詞-並立助詞\t\t',
 '人工知能\tジンコウチノウ\t人工知能\t名詞-固有名詞-一般\t\t',
 'の\tノ\tの\t助詞-連体化\t\t',
 '教育\tキョウイク\t教育\t名詞-サ変接続\t\t',
 'を\tヲ\tを\t助詞-格助詞-一般\t\t',
 '行っ\tオコナッ\t行う\t動詞-自立\t五段・ワ行促音便\t連用タ接続',
 'て\tテ\tて\t助詞-接続助詞\t\t',
 'い\tイ\tいる\t動詞-非自立\t一段\t連用形',
 'ます\tマス\tます\t助動詞\t特殊・マス\t基本形',
 '。\t。\t。\t記号-句点\t\t']

In [20]:
res.split('\n')[0].split('\t')[3]

'名詞-一般'

In [46]:
# 名詞であるもののみをリスト化する
key_word = '名詞'

nouns = []
words = res.split('\n')[:-2]

for word in words:
    part = word.split('\t')
    if key_word in part[3]:
        nouns.append(part[0])
nouns

['キカガク', 'ディープラーニング', '機械学習', '人工知能', '教育']

In [47]:
# ワンライナー
nouns = [word.split('\t')[0] for word in words if key_word in word.split('\t')[3]]
nouns

['キカガク', 'ディープラーニング', '機械学習', '人工知能', '教育']

演習

In [23]:
text1 = 'キカガクでは、ディープラーニングを含んだ機械学習や人工知能の教育を行っています。'
text2 = '代表の吉崎は大学院では機械学習・ロボットのシステム制御、画像処理の研究に携わっていました。'
text3 = '機械学習、システム制御、画像処理ではすべて線形代数とプログラミングが不可欠になります。'

In [53]:
def get_nouns(text, key_word='名詞'):
    nouns = []
    res = mecab.parse(text)
    words = res.split('\n')[:-2]

    for word in words:
        part = word.split('\t')
        if key_word in part[3]:
            nouns.append(part[0])
    return nouns

In [54]:
get_nouns(text)

['キカガク', 'ディープラーニング', '機械学習', '人工知能', '教育']

In [57]:
get_nouns(text2)

['代表', '吉崎', '大学院', '機械学習', 'ロボット', 'システム', '制御', '画像処理', '研究']

In [56]:
get_nouns(text3)

['機械学習', 'システム', '制御', '画像処理', 'すべて', '線形代数', 'プログラミング', '不可欠']

In [72]:
get_nouns("My name is Yoshizaki.")

['My', 'name', 'is', 'Yoshizaki']

In [69]:
get_nouns("내 이름은 요시 자키입니다.")

[]

In [73]:
get_nouns('我的名字是吉崎')

['我', '的', '名字', '是吉', '崎']

特徴量に変換

In [74]:
from gensim import corpora, matutils

In [78]:
text1 = 'キカガクでは、ディープラーニングを含んだ機械学習や人工知能の教育を行っています。'
text2 = '代表の吉崎は大学院では機械学習・ロボットのシステム制御、画像処理の研究に携わっていました。'
text3 = '機械学習、システム制御、画像処理ではすべて線形代数とプログラミングが不可欠になります。'
text_list = [text1, text2, text3]

word_collect = [get_nouns(text_i) for text_i in text_list]
word_collect

[['キカガク', 'ディープラーニング', '機械学習', '人工知能', '教育'],
 ['代表', '吉崎', '大学院', '機械学習', 'ロボット', 'システム', '制御', '画像処理', '研究'],
 ['機械学習', 'システム', '制御', '画像処理', 'すべて', '線形代数', 'プログラミング', '不可欠']]

In [93]:
nouns1, nouns2, nouns3 = word_collect

In [80]:
dictionary = corpora.Dictionary(word_collect)
dictionary

In [81]:
len(dictionary)

17

In [85]:
dictionary.keys()

[5, 3, 2, 16, 8, 9, 6, 11, 4, 13, 1, 10, 12, 0, 14, 7, 15]

In [88]:
for word in dictionary.items():
    print(word)

(5, 'システム')
(3, '教育')
(2, '機械学習')
(16, 'プログラミング')
(8, 'ロボット')
(9, '吉崎')
(6, '画像処理')
(11, '研究')
(4, 'ディープラーニング')
(13, '線形代数')
(1, '人工知能')
(10, '制御')
(12, '代表')
(0, 'キカガク')
(14, 'すべて')
(7, '大学院')
(15, '不可欠')


In [90]:
dictionary.doc2bow(['aiueo'])

[]

In [96]:
bow1_id = dictionary.doc2bow(nouns1)
bow2_id = dictionary.doc2bow(nouns2)
bow3_id = dictionary.doc2bow(nouns3)

In [97]:
bow1_id

[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1)]

In [102]:
n_words = len(dictionary)
bow = matutils.corpus2dense([bow1_id], n_words)
bow

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [103]:
bow.shape

(17, 1)

In [106]:
bow = bow.T
bow.shape

(1, 17)

In [109]:
bow[0].shape

(17,)

In [120]:
# 入力: [text1, text2, ...]
def get_bow(text_list):
    '''
    arguments: list
        [text1, text2, ...]
        
    returns:
        bow: list
        dictionary: dictionary
    '''
    
    # 単語を抜き出したリストを作成
    word_collect = [get_nouns(text_i) for text_i in text_list]

    # ユニークな辞書を作成
    dictionary = corpora.Dictionary(word_collect)
    
    bow = []
    # Bag of Wordsを計算
    n_words = len(dictionary)
    for nouns_i in word_collect:
        bow_i = dictionary.doc2bow(nouns_i)
        bow.append(matutils.corpus2dense([bow_i], n_words).T[0])
    
    return bow, dictionary

In [121]:
bow, dictionary = get_bow(text_list)
bow

[array([1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=float32),
 array([0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       dtype=float32),
 array([0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 1.],
       dtype=float32)]

In [119]:
for i in dictionary.items():
    print(i)

(5, 'システム')
(3, '教育')
(2, '機械学習')
(16, 'プログラミング')
(8, 'ロボット')
(9, '吉崎')
(6, '画像処理')
(11, '研究')
(4, 'ディープラーニング')
(13, '線形代数')
(1, '人工知能')
(10, '制御')
(12, '代表')
(0, 'キカガク')
(14, 'すべて')
(7, '大学院')
(15, '不可欠')


In [125]:
import numpy as np
np.array(bow).shape

(3, 17)